services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5400:5400"
    env_file:
      - ./.env.production
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started

  redis:
    image: redis:alpine
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    env_file:
      - ./.env.production
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./.env.production
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 10

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD &&
      mc mb -p local/$S3_BUCKET || true &&
      mc mb -p local/posts || true &&
      mc anonymous set download local/$S3_BUCKET &&
      mc anonymous set download local/posts
      "
    env_file:
      - ./.env.production

volumes:
  postgres_data:
  redis_data:
  minio_data:
